# Accuracy Metric

In [3]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv('Datasets/heart.csv')
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [28]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [57]:
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [30]:
lor = LogisticRegression()
dt = DecisionTreeClassifier()

lor.fit(X_train,y_train)
dt.fit(X_train,y_train)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [31]:
y_pred1 = lor.predict(X_test)
y_pred2 = dt.predict(X_test)

In [ ]:
y_pred1

In [59]:
y_test

546    0
980    1
908    0
577    0
846    1
      ..
922    1
832    1
451    1
775    1
926    0
Name: target, Length: 205, dtype: int64

In [58]:
X_test

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
546   70    1   0       130   322    0        0      109      0      2.4   
980   57    1   0       140   192    0        1      148      0      0.4   
908   62    1   0       120   267    0        1       99      1      1.8   
577   70    1   0       130   322    0        0      109      0      2.4   
846   35    0   0       138   183    0        1      182      0      1.4   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
922   44    1   1       120   263    0        1      173      0      0.0   
832   68    1   2       118   277    0        1      151      0      1.0   
451   49    0   1       134   271    0        1      162      0      0.0   
775   51    1   2       100   222    0        1      143      1      1.2   
926   54    1   0       110   206    0        0      108      1      0.0   

     slope  ca  thal  
546      1   3     2  
980      1   0     1  
908      1   2     3  
577      1   3     2  
846      2   0     2  
..     ...  ..   ...  
922      2   0     3  
832      2   1     3  
451      1   0     2  
775      1   0     2  
926      1   1     2  

[205 rows x 13 columns]

In [60]:
from sklearn.metrics import accuracy_score

print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.8390243902439024
Accuracy of Decision Trees 0.9804878048780488


# Confusion Matrix

In [33]:
from sklearn.metrics import confusion_matrix

In [34]:
confusion_matrix(y_test,y_pred1)

array([[82, 23],
       [10, 90]], dtype=int64)

In [35]:
confusion_matrix(y_test,y_pred2)

array([[101,   4],
       [  0, 100]], dtype=int64)

In [36]:
# for multi_classifcation

In [37]:
iris = pd.read_csv('Datasets/iris.csv')
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [38]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
iris['Species'] = encoder.fit_transform(iris['Species'])

In [39]:
iris.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0   1            5.1           3.5            1.4           0.2        0
1   2            4.9           3.0            1.4           0.2        0
2   3            4.7           3.2            1.3           0.2        0
3   4            4.6           3.1            1.5           0.2        0
4   5            5.0           3.6            1.4           0.2        0

In [40]:
X_train,X_test,y_train,y_test = train_test_split(iris.iloc[:,0:-1],iris.iloc[:,-1],test_size=0.2,random_state=1)

In [41]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [42]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [43]:
y_predict1 = clf1.predict(X_test)
y_predict2 = clf2.predict(X_test)

In [44]:
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_predict1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_predict2))

Accuracy of Logistic Regression 1.0
Accuracy of Decision Trees 0.9666666666666667


In [45]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_predict1),columns=list(range(0,3)))

Logistic Regression Confusion Matrix



0   1  2
0  11   0  0
1   0  13  0
2   0   0  6

In [46]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_predict2),columns=list(range(0,3)))

Decision Tree Confusion Matrix



0   1  2
0  11   0  0
1   0  12  1
2   0   0  6

# Precision, Recall, f1 Score

In [49]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [52]:
len(y_test)

30

In [53]:
len(y_pred1)

205

In [61]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
    0   1
0  82  23
1  10  90
--------------------------------------------------
Precision -  0.7964601769911505
Recall -  0.9
F1 score -  0.8450704225352113


In [62]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,2)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
     0    1
0  101    4
1    0  100
--------------------------------------------------
Precision -  0.9615384615384616
Recall -  1.0
F1 score -  0.9803921568627451


In [63]:
precision_score(y_test,y_pred1,average=None)

array([0.89130435, 0.79646018])

In [64]:
precision_score(y_test,y_pred2,average=None)

array([1.        , 0.96153846])

In [65]:
recall_score(y_test,y_pred2,average=None)

array([0.96190476, 1.        ])

# mnist data set

In [66]:
df1 = pd.read_csv('Datasets/digit_recognizer_train.csv')

In [68]:
df1.head()

label  pixel0  pixel1  pixel2  pixel3  pixel4  pixel5  pixel6  pixel7  \
0      1       0       0       0       0       0       0       0       0   
1      0       0       0       0       0       0       0       0       0   
2      1       0       0       0       0       0       0       0       0   
3      4       0       0       0       0       0       0       0       0   
4      0       0       0       0       0       0       0       0       0   

   pixel8  ...  pixel774  pixel775  pixel776  pixel777  pixel778  pixel779  \
0       0  ...         0         0         0         0         0         0   
1       0  ...         0         0         0         0         0         0   
2       0  ...         0         0         0         0         0         0   
3       0  ...         0         0         0         0         0         0   
4       0  ...         0         0         0         0         0         0   

   pixel780  pixel781  pixel782  pixel783  
0         0         0         0         0  
1         0         0         0         0  
2         0         0         0         0  
3         0         0         0         0  
4         0         0         0         0  

[5 rows x 785 columns]

In [72]:
df1.shape

(42000, 785)

In [70]:
df1['label'].value_counts().sort_index()

0    4132
1    4684
2    4177
3    4351
4    4072
5    3795
6    4137
7    4401
8    4063
9    4188
Name: label, dtype: int64

In [132]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df1.iloc[:,1:],df1.iloc[:,0],test_size=0.2,random_state=2)

In [133]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [134]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [135]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [136]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [137]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9145238095238095
Accuracy of Decision Trees 0.8520238095238095


In [139]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  791    0    1    0    1    9   11    1    6    1
1    0  938    2    4    0    3    0    3   12    0
2    2    9  745   16    9    4   13   13   15    3
3    1    4   19  763    0   36    5    5   20   11
4    2    5    4    0  804    1    7    3    9   21
5    9    3    4   23   10  610   15   10   34   11
6   12    4   12    1    7    8  789    0    5    1
7    3    2   13    6    4    2    0  812    2   29
8   11   12   13   18    1   21    6    6  694   11
9    3    6    2   14   25    4    0   37    7  736

In [140]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix



0    1    2    3    4    5    6    7    8    9
0  754    0   11    5    6   15    9    2   12    7
1    0  903    9   11    8    4    7    7   11    2
2   10   18  666   32   22   19   13   20   21    8
3    7    9   29  691    7   46    9   16   29   21
4    7    5    7    7  738   12   13    9   19   39
5   12    3   11   37    9  583   22    8   21   23
6    8    2   12    7    9   28  752    0   14    7
7    3   10   20   16    7    3    2  780   11   21
8   16   10   21   35   21   37   14    6  612   21
9    5    7    6   21   43   20    4   29   21  678

In [141]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [143]:
precision_score(y_test,y_pred1,average=None)

array([0.94844125, 0.95422177, 0.91411043, 0.90295858, 0.93379791,
       0.8739255 , 0.93262411, 0.91235955, 0.86318408, 0.89320388])

In [142]:
precision_score(y_test,y_pred1,average='weighted')

0.9142150713630827

In [144]:
recall_score(y_test,y_pred1,average=None)

array([0.9634592 , 0.97505198, 0.8986731 , 0.88310185, 0.93925234,
       0.83676269, 0.94040524, 0.930126  , 0.87515763, 0.882494  ])

In [145]:
recall_score(y_test,y_pred1,average='weighted')

0.9145238095238095

In [146]:
f1_score(y_test,y_pred1,average=None)

array([0.95589124, 0.96452442, 0.90632603, 0.89291984, 0.93651718,
       0.85494043, 0.93649852, 0.92115712, 0.86912962, 0.88781665])

In [147]:
f1_score(y_test,y_pred1,average='weighted')

0.9142794994052751

In [148]:
from sklearn.metrics import classification_report

print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       821
           1       0.95      0.98      0.96       962
           2       0.91      0.90      0.91       829
           3       0.90      0.88      0.89       864
           4       0.93      0.94      0.94       856
           5       0.87      0.84      0.85       729
           6       0.93      0.94      0.94       839
           7       0.91      0.93      0.92       873
           8       0.86      0.88      0.87       793
           9       0.89      0.88      0.89       834

    accuracy                           0.91      8400
   macro avg       0.91      0.91      0.91      8400
weighted avg       0.91      0.91      0.91      8400



In [149]:
print(classification_report(y_test,y_pred2))

              precision    recall  f1-score   support

           0       0.92      0.92      0.92       821
           1       0.93      0.94      0.94       962
           2       0.84      0.80      0.82       829
           3       0.80      0.80      0.80       864
           4       0.85      0.86      0.86       856
           5       0.76      0.80      0.78       729
           6       0.89      0.90      0.89       839
           7       0.89      0.89      0.89       873
           8       0.79      0.77      0.78       793
           9       0.82      0.81      0.82       834

    accuracy                           0.85      8400
   macro avg       0.85      0.85      0.85      8400
weighted avg       0.85      0.85      0.85      8400

